version: "3"
services:
  server:
    command: sh -c "adonis migration:run && adonis serve --dev"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=development
      - ENV_PATH=.env
    depends_on: 
      - db_mysql
  db_mysql:
    image: mysql:latest
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    env_file:  
        - ../.env
    expose: 
        - 3307
    ports: 
        - 3307:3307
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
    container_name: mysql_db
