version: "3"
services:
  server:
    command: adonis serve --dev
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=development
      - ENV_PATH=.env
